server:
  port: 8080

grpc:
  server:
    port: 9090
    enable-keep-alive: true
    permit-keep-alive-without-calls: true
  client:
    hello:
      address: localhost:9090
      negotiationType: PLAINTEXT
